---
title: "Balance Assessment"
description: |
author:
  - name: Jacob Simmering, PhD 
    url: https://jacobsimmering.com
    affiliation: University of Iowa
    affiliation_url: https://uiowa.edu
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pkg-load}
library(tidyverse)
library(survival)
library(tableone)
library(effectsize)
library(patchwork)
```

```{r gen-outcomes}
if (Sys.info()["sysname"] == "Darwin") {
  shared_dir <- "/Volumes"
} else {
  shared_dir <- "/Shared"
}

model_data <- read_rds(glue::glue("/{shared_dir}/lss_jsimmeri/LBD/treated_model_data_women.rds"))

outcomes <- model_data %>%
  select(enrolid, female, drug, develops_pd, survival_time)
```

```{r load-matches}
tz_tam_matches_male <- read_rds(glue::glue("{shared_dir}/lss_jsimmeri/LBD/matches_tz_tam_2rx_male.rds"))
tz_5ari_matches_male <- read_rds(glue::glue("{shared_dir}/lss_jsimmeri/LBD/matches_tz_5ari_2rx_male.rds"))
tam_5ari_matches_male <- read_rds(glue::glue("{shared_dir}/lss_jsimmeri/LBD/matches_tam_5ari_2rx_male.rds"))

tz_tam_matches_female <- read_rds(glue::glue("{shared_dir}/lss_jsimmeri/LBD/matches_tz_tam_2rx_female.rds"))
tz_5ari_matches_female <- read_rds(glue::glue("{shared_dir}/lss_jsimmeri/LBD/matches_tz_5ari_2rx_female.rds"))
tam_5ari_matches_female <- read_rds(glue::glue("{shared_dir}/lss_jsimmeri/LBD/matches_tam_5ari_2rx_female.rds"))
```

```{r make-paired-outcomes}
outcomes_tz_tam_male <- inner_join(outcomes, tz_tam_matches_male, by = c("enrolid"))
outcomes_tz_5ari_male <- inner_join(outcomes, tz_5ari_matches_male, by = c("enrolid"))
outcomes_tam_5ari_male <- inner_join(outcomes, tam_5ari_matches_male, by = c("enrolid"))

outcomes_tz_tam_female <- inner_join(outcomes, tz_tam_matches_female, by = c("enrolid"))
outcomes_tz_5ari_female <- inner_join(outcomes, tz_5ari_matches_female, by = c("enrolid"))
outcomes_tam_5ari_female <- inner_join(outcomes, tam_5ari_matches_female, by = c("enrolid"))
```

## Balance Assessment
First, look at male users of Tz/Dz/Az versus female users:

```{r}
vars <- c("age", "start_year", 
          "cm_elix_Alcohol", "cm_elix_Anemia", "cm_elix_BloodLoss",
          "cm_elix_CHF", "cm_elix_Coagulopathy", "cm_elix_DM",
          "cm_elix_DMcx", "cm_elix_Depression", "cm_elix_Drugs",
          "cm_elix_FluidsLytes", "cm_elix_HIV", "cm_elix_HTN",
          "cm_elix_HTNcx", "cm_elix_Hypothyroid", "cm_elix_Liver",
           "cm_elix_Lymphoma", "cm_elix_Mets", "cm_elix_NeuroOther",
           "cm_elix_Obesity", "cm_elix_PHTN", "cm_elix_PUD",
           "cm_elix_PVD", "cm_elix_Paralysis", "cm_elix_Psychoses",
           "cm_elix_Pulmonary", "cm_elix_Renal", "cm_elix_Rheumatic",
           "cm_elix_Tumor", "cm_elix_Valvular", "cm_elix_WeightLoss",
           "cm_abnormal_psa", "cm_anxiety", "cm_bph",
           "cm_ed", "cm_orthostatic", "cm_other_hypo",
           "cm_slow_stream", "psa_measured", "uroflow",
           "cystometrogram", "in_rate", "in_days_rate",
           "out_rate", "mean_ndx", "out_dx_rate", "develops_pd")

non_normal_vars <- c("age", "start_year", "in_rate", "in_days_rate", "out_rate",
                     "mean_ndx", "out_dx_rate")

male_vs_female_tz <- CreateTableOne(
  vars = vars,
  strata = "female",
  data = model_data |> 
    mutate(start_year = as.numeric(as.character(start_year))) |>
    filter(drug == "tz/dz/az") |>
    mutate(female = ifelse(female, "Female", "Male"))
)

print(male_vs_female_tz,
      nonnormal = non_normal_vars,
      smd = TRUE)
```

Second, compare that to men on Tz/Dz/Az versus men on tamsulosin:

```{r}
male_tz_vs_male_tam <- CreateTableOne(
  vars = vars,
  strata = "drug",
  data = model_data |> 
    mutate(start_year = as.numeric(as.character(start_year))) |>
    filter(female == 0) |>
    filter(drug %in% c("tz/dz/az", "tamsulosin"))
)

print(male_tz_vs_male_tam,
      nonnormal = non_normal_vars,
      smd = TRUE)
```

Or graphically:

```{r}
cohens_d_no_ci <- function(data, variable, by, conf.level = 0.95, ...) {
  d <- cohens_d(data[[variable]] ~ data[[by]], ci = conf.level) |>
    as_tibble() |>
    select(
      estimate = Cohens_d
    )
  return(d)
}

cohens_w <- function(data, variable, by, conf.level, ...) {
  counts <- data |>
    group_by(!!sym(variable), !!sym(by)) |>
    count() |>
    ungroup() |>
    pivot_wider(
      names_from = !!sym(variable),
      values_from = "n"
    )

  xsq_test <- chisq.test(as.matrix(counts[, -1]))
  w <- effectsize(xsq_test, type = "cohens_w", ci = NA) |>
    as_tibble() |>
    rename(estimate = Cohens_w)

  return(w)
}

male_vs_female_tz_data <- model_data |> 
    mutate(start_year = as.numeric(as.character(start_year))) |>
    filter(drug == "tz/dz/az") |>
    mutate(female = ifelse(female, "Female", "Male"))

male_tz_vs_male_tam_data <- model_data |> 
    mutate(start_year = as.numeric(as.character(start_year))) |>
    filter(female == 0) |>
    filter(drug %in% c("tz/dz/az", "tamsulosin"))

numeric_vars <- c("age", "start_year", "in_rate", "in_days_rate", "out_rate", 
                  "mean_ndx", "out_dx_rate")
standardized_difference <- vector("list", NROW(vars))
i <- 1
for (variable in vars) {
  if (variable %in% numeric_vars) {
    std_diff_male_vs_female <- cohens_d_no_ci(
      male_vs_female_tz_data, variable, "female", 0.95
    )

    std_diff_male_tz_vs_tam <- cohens_d_no_ci(
      male_tz_vs_male_tam_data, variable, "drug", 0.95
    )
  } else {
    std_diff_male_vs_female <- cohens_w(
      male_vs_female_tz_data, variable, "female", 0.95
    )

    std_diff_male_tz_vs_tam <- cohens_w(
      male_tz_vs_male_tam_data, variable, "drug", 0.95
    )
  }

  standardized_difference[[i]] <- tibble(
    variable = variable,
    comparison = c("male vs female", "tz vs tam"),
    std_diff = c(std_diff_male_vs_female$estimate, std_diff_male_tz_vs_tam$estimate)
  )
  i <- i + 1
}

variable_labels <- tribble(
  ~ variable, ~ variable_label, ~ variable_group, ~ group_level,
  "age", "Age at Index Date", "Baseline Characteristics", 1,
  "start_year", "Year of Index Date", "Baseline Characteristics", 1,
  "cm_elix_Alcohol", "Alcohol Abuse", "Elixhauser Comorbidities", 3,
  "cm_elix_Anemia", "Anemia", "Elixhauser Comorbidities", 3,
  "cm_elix_BloodLoss", "Blood Loss", "Elixhauser Comorbidities", 3,
  "cm_elix_CHF", "Heart Failure", "Elixhauser Comorbidities", 3,
  "cm_elix_Coagulopathy", "Coagulopathy", "Elixhauser Comorbidities", 3,
  "cm_elix_DM", "Diabetes", "Elixhauser Comorbidities", 3,
  "cm_elix_DMcx", "Diabetes with Complications", "Elixhauser Comorbidities", 3,
  "cm_elix_Depression", "Depression", "Elixhauser Comorbidities", 3,
  "cm_elix_Drugs", "Drug Abuse", "Elixhauser Comorbidities", 3,
  "cm_elix_FluidsLytes", "Fluid and Electrolyte Disorders", "Elixhauser Comorbidities", 3,
  "cm_elix_HIV", "HIV", "Elixhauser Comorbidities", 3,
  "cm_elix_HTN", "HTN", "Elixhauser Comorbidities", 3,
  "cm_elix_HTNcx", "HTN with Complications", "Elixhauser Comorbidities", 3,
  "cm_elix_Hypothyroid", "Hypothyroidism", "Elixhauser Comorbidities", 3,
  "cm_elix_Liver", "Liver Disease", "Elixhauser Comorbidities", 3,
  "cm_elix_Lymphoma", "Lymphoma", "Elixhauser Comorbidities", 3,
  "cm_elix_Mets", "Metastatic Cancer", "Elixhauser Comorbidities", 3,
  "cm_elix_NeuroOther", "Other Neurological Disease", "Elixhauser Comorbidities", 3,
  "cm_elix_Obesity", "Obesity", "Elixhauser Comorbidities", 3,
  "cm_elix_PHTN", "Pulm. HTN", "Elixhauser Comorbidities", 3,
  "cm_elix_PUD", "Peptic Ulcer Disease", "Elixhauser Comorbidities", 3,
  "cm_elix_PVD", "Peripheral Vascular Disease", "Elixhauser Comorbidities", 3,
  "cm_elix_Paralysis", "Paralysis", "Elixhauser Comorbidities", 3,
  "cm_elix_Psychoses", "Psychoses", "Elixhauser Comorbidities", 3,
  "cm_elix_Pulmonary", "COPD", "Elixhauser Comorbidities", 3,
  "cm_elix_Renal", "Renal Disease", "Elixhauser Comorbidities", 3,
  "cm_elix_Rheumatic", "Rheumatic Disease", "Elixhauser Comorbidities", 3,
  "cm_elix_Tumor", "Solid Tumor", "Elixhauser Comorbidities", 3,
  "cm_elix_Valvular", "Valvular Disease", "Elixhauser Comorbidities", 3,
  "cm_elix_WeightLoss", "Weight Loss", "Elixhauser Comorbidities", 3,
  "cm_abnormal_psa", "Abnormal PSA", "BPH/Urinary Symptoms", 4,
  "cm_anxiety", "Anxiety", "Possible DLB Prodromal Signs", 5,
  "cm_bph", "Diagnosis of BPH", "BPH/Urinary Symptoms", 4,
  "cm_ed", "Erectile Dysfunction", "Possible DLB Prodromal Signs", 5,
  "cm_orthostatic", "Orthostatic Hypotension", "Possible DLB Prodromal Signs", 5,
  "cm_other_hypo", "Other Hypotension", "Possible DLB Prodromal Signs", 5,
  "cm_slow_stream", "Slow Urinary Stream", "BPH/Urinary Symptoms", 4,
  "psa_measured", "PSA Measurement", "BPH/Urinary Symptoms", 4,
  "uroflow", "Uroflow Performed", "BPH/Urinary Symptoms", 4,
  "cystometrogram", "Cystometrogram Performed", "BPH/Urinary Symptoms", 4,
  "in_rate", "Rate of Inpatient Stays", "Health Care Utilization", 2,
  "in_days_rate", "Rate of Inpatient Days", "Health Care Utilization", 2,
  "out_rate", "Rate of Outpatient Encounters", "Health Care Utilization", 2,
  "mean_ndx", "Mean Num. of DX per\nOutpatient Encounter", "Health Care Utilization", 2,
  "out_dx_rate", "Rate of Unique Outpatient DX", "Health Care Utilization", 2,
  )

standardized_difference <- standardized_difference |>
  bind_rows() |>
  filter(variable != "develops_pd") |>
  inner_join(variable_labels, join_by(variable))

baseline_characteristics <- standardized_difference |>
  filter(variable_group == "Baseline Characteristics") |>
  ggplot(
    aes(
      x = abs(std_diff),
      y = variable_label,
      color = comparison
    )
  ) + 
  geom_point() +
  theme_minimal() +
  theme(legend.position = "none") + 
  labs(x = "", y = "", title = "Baseline Characteristics") +
  scale_x_continuous(limits = c(0, 0.75)) +
  geom_vline(xintercept = 0.1, linetype = 2) + 
  geom_vline(xintercept = 0.2, linetype = 3) + 
  geom_vline(xintercept = 0.5, linetype = 4)

utilization <- standardized_difference |>
  filter(variable_group == "Health Care Utilization") |>
  ggplot(
    aes(
      x = abs(std_diff),
      y = variable_label,
      color = comparison
    )
  ) + 
  geom_point() +
  theme_minimal() +
  theme(legend.position = "none") + 
  labs(x = "", y = "", title = "Health Care Utilization") +
  scale_x_continuous(limits = c(0, 0.75)) + 
  geom_vline(xintercept = 0.1, linetype = 2) + 
  geom_vline(xintercept = 0.2, linetype = 3) + 
  geom_vline(xintercept = 0.5, linetype = 4)

prodromal <- standardized_difference |>
  filter(variable_group == "Possible DLB Prodromal Signs") |>
  ggplot(
    aes(
      x = abs(std_diff),
      y = variable_label,
      color = comparison
    )
  ) + 
  geom_point() +
  theme_minimal() +
  theme(legend.position = "none") + 
  labs(x = "", y = "", title = "Possible DLB Prodromal Signs") +
  scale_x_continuous(limits = c(0, 0.75)) + 
  geom_vline(xintercept = 0.1, linetype = 2) + 
  geom_vline(xintercept = 0.2, linetype = 3) + 
  geom_vline(xintercept = 0.5, linetype = 4)

bph_luts <- standardized_difference |>
  filter(variable_group == "BPH/Urinary Symptoms") |>
  ggplot(
    aes(
      x = abs(std_diff),
      y = variable_label,
      color = comparison
    )
  ) + 
  geom_point() +
  theme_minimal() +
  theme(legend.position = "none") + 
  labs(x = "", y = "", title = "BPH/Urinary Symptoms") +
  scale_x_continuous(limits = c(0, 0.75)) + 
  geom_vline(xintercept = 0.1, linetype = 2) + 
  geom_vline(xintercept = 0.2, linetype = 3) + 
  geom_vline(xintercept = 0.5, linetype = 4)

elixhauser <- standardized_difference |>
  filter(variable_group == "Elixhauser Comorbidities") |>
  ggplot(
    aes(
      x = abs(std_diff),
      y = variable_label,
      color = comparison
    )
  ) + 
  geom_point() +
  theme_minimal() +
  theme(legend.position = "none") + 
  labs(x = "", y = "", title = "Elixhauser Comorbidities") +
  scale_x_continuous(limits = c(0, 0.75)) + 
  geom_vline(xintercept = 0.1, linetype = 2) + 
  geom_vline(xintercept = 0.2, linetype = 3) + 
  geom_vline(xintercept = 0.5, linetype = 4)

baseline_characteristics / utilization / prodromal / bph_luts / elixhauser + 
  plot_layout(
    design = "AA
     AA
     BB
     BB
     BB
     BB
     BB
     CC
     CC
     CC
     CC
     DD
     DD
     DD
     DD
     DD
     DD
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE
     EE"
  )

ggsave("~/smd_male_female.png", width = 8.5, height = 11)
```


```{r}

tab_tz_tam_female_matched <- CreateTableOne(
  vars = vars,
  strata = "drug",
  data = model_data |> 
    filter(enrolid %in% outcomes_tz_tam_female$enrolid) |>
    mutate(start_year = as.numeric(start_year))
)

print(tab_tz_tam_female_matched,
      nonnormal = non_normal_vars,
      smd = TRUE)
```

## Tz/Dz/Az versus Tamsulosin

```{r}
vars <- c("develops_pd")
tab_tz_tam_female <- CreateTableOne(
  vars = vars,
  strata = "drug",
  data = outcomes_tz_tam_female
)
print(tab_tz_tam_female, formatOptions = list(big.mark = ","))
```

```{r tz-vs-tam}
coxph(
  Surv(survival_time, develops_pd) ~ drug,
  data = outcomes_tz_tam_female,
  cluster = pair_id,
  robust = TRUE
)

coxph(
  Surv(survival_time, develops_pd) ~ drug,
  data = outcomes_tz_tam_female,
  cluster = pair_id,
  robust = TRUE
)
```

```{r}
outcomes_tz_tam |>
  group_by(drug, female) |>
  summarize(
    n = n(),
    time = sum(survival_time / 365),
    cases = sum(develops_pd),
    incidence = cases / time * 10000
  )

coxph(Surv(survival_time, develops_pd) ~ drug * female, 
      data = outcomes_tz_tam, 
      cluster = pair_id,
      robust = TRUE) %>%
  summary()

outcomes_tz_5ari |>
  group_by(drug, female) |>
  summarize(
    n = n(),
    time = sum(survival_time / 365),
    cases = sum(develops_pd),
    incidence = cases / time * 10000
  )

coxph(Surv(survival_time, develops_pd) ~ drug * female, 
      data = outcomes_tz_5ari, 
      cluster = pair_id,
      robust = TRUE) %>%
  summary()

outcomes_tam_5ari |>
  group_by(drug, female) |>
  summarize(
    n = n(),
    time = sum(survival_time / 365),
    cases = sum(develops_pd),
    incidence = cases / time * 10000
  )

coxph(Surv(survival_time, develops_pd) ~ drug * female, 
      data = outcomes_tam_5ari, 
      cluster = pair_id,
      robust = TRUE) %>%
  summary()
```

```{r}
survfit(
  Surv(survival_time, develops_pd) ~ drug + female, 
  data = outcomes_tz_tam) |>
  broom::tidy() |>
  mutate(
    treatment = ifelse(stringr::str_detect(strata, "tz/dz/az"), "Tz/Dz/Az", "Tamsulosin"),
    gender = ifelse(stringr::str_sub(strata, -1, -1) == "0", "Male", "Female")
  ) |>
  ggplot(
    aes(
      x = time / 365, 
      y = estimate,
      ymin = conf.low,
      ymax = conf.high,
      color = treatment,
      fill = treatment
    )
  ) + 
  geom_step() + 
  geom_ribbon(alpha = 0.33, linetype = 0) + 
  facet_wrap(~ gender)
ggsave("~/dlb_male_female_km_matched.png")
```

```{r}
survfit(
  Surv(survival_time, develops_pd) ~ drug + female, 
  data = outcomes |> filter(drug %in% c("tz/dz/az", "tamsulosin"))) |>
  broom::tidy() |>
  mutate(
    treatment = ifelse(stringr::str_detect(strata, "tz/dz/az"), "Tz/Dz/Az", "Tamsulosin"),
    gender = ifelse(stringr::str_sub(strata, -1, -1) == "0", "Male", "Female")
  ) |>
  ggplot(
    aes(
      x = time / 365, 
      y = estimate,
      ymin = conf.low,
      ymax = conf.high,
      color = treatment,
      fill = treatment
    )
  ) + 
  geom_step() + 
  geom_ribbon(alpha = 0.33, linetype = 0) + 
  facet_wrap(~ gender)
ggsave("~/dlb_male_female_km_raw.png")
```